// const countries = {
//   "am-ET": "Amharic",
//   "ar-SA": "Arabic",
//   "be-BY": "Bielarus",
//   "bem-ZM": "Bemba",
//   "bi-VU": "Bislama",
//   "bjs-BB": "Bajan",
//   "bn-IN": "Bengali",
//   "bo-CN": "Tibetan",
//   "br-FR": "Breton",
//   "bs-BA": "Bosnian",
//   "ca-ES": "Catalan",
//   "cop-EG": "Coptic",
//   "cs-CZ": "Czech",
//   "cy-GB": "Welsh",
//   "da-DK": "Danish",
//   "dz-BT": "Dzongkha",
//   "de-DE": "German",
//   "dv-MV": "Maldivian",
//   "el-GR": "Greek",
//   "en-GB": "English",
//   "es-ES": "Spanish",
//   "et-EE": "Estonian",
//   "eu-ES": "Basque",
//   "fa-IR": "Persian",
//   "fi-FI": "Finnish",
//   "fn-FNG": "Fanagalo",
//   "fo-FO": "Faroese",
//   "fr-FR": "French",
//   "gl-ES": "Galician",
//   "gu-IN": "Gujarati",
//   "ha-NE": "Hausa",
//   "he-IL": "Hebrew",
//   "hi-IN": "Hindi",
//   "hr-HR": "Croatian",
//   "hu-HU": "Hungarian",
//   "id-ID": "Indonesian",
//   "is-IS": "Icelandic",
//   "it-IT": "Italian",
//   "ja-JP": "Japanese",
//   "kk-KZ": "Kazakh",
//   "km-KM": "Khmer",
//   "kn-IN": "Kannada",
//   "ko-KR": "Korean",
//   "ku-TR": "Kurdish",
//   "ky-KG": "Kyrgyz",
//   "la-VA": "Latin",
//   "lo-LA": "Lao",
//   "lv-LV": "Latvian",
//   "men-SL": "Mende",
//   "mg-MG": "Malagasy",
//   "mi-NZ": "Maori",
//   "ms-MY": "Malay",
//   "mt-MT": "Maltese",
//   "my-MM": "Burmese",
//   "ne-NP": "Nepali",
//   "niu-NU": "Niuean",
//   "nl-NL": "Dutch",
//   "no-NO": "Norwegian",
//   "ny-MW": "Nyanja",
//   "ur-PK": "Pakistani",
//   "pau-PW": "Palauan",
//   "pa-IN": "Panjabi",
//   "ps-PK": "Pashto",
//   "pis-SB": "Pijin",
//   "pl-PL": "Polish",
//   "pt-PT": "Portuguese",
//   "rn-BI": "Kirundi",
//   "ro-RO": "Romanian",
//   "ru-RU": "Russian",
//   "sg-CF": "Sango",
//   "si-LK": "Sinhala",
//   "sk-SK": "Slovak",
//   "sm-WS": "Samoan",
//   "sn-ZW": "Shona",
//   "so-SO": "Somali",
//   "sq-AL": "Albanian",
//   "sr-RS": "Serbian",
//   "sv-SE": "Swedish",
//   "sw-SZ": "Swahili",
//   "ta-LK": "Tamil",
//   "te-IN": "Telugu",
//   "tet-TL": "Tetum",
//   "tg-TJ": "Tajik",
//   "th-TH": "Thai",
//   "ti-TI": "Tigrinya",
//   "tk-TM": "Turkmen",
//   "tl-PH": "Tagalog",
//   "tn-BW": "Tswana",
//   "to-TO": "Tongan",
//   "tr-TR": "Turkish",
//   "uk-UA": "Ukrainian",
//   "uz-UZ": "Uzbek",
//   "vi-VN": "Vietnamese",
//   "wo-SN": "Wolof",
//   "xh-ZA": "Xhosa",
//   "yi-YD": "Yiddish",
//   "zu-ZA": "Zulu",
// };

const countries = [
  { code: "ru", name: "Russian" },
  { code: "en", name: "English" },
  { code: "de", name: "Deutsch" },
  { code: "es", name: "Español" },
  { code: "fr", name: "Français" },
  { code: "it", name: "Italiano" },
  { code: "pt", name: "Português" },
  { code: "nl", name: "Nederlands" },
  { code: "sv", name: "Svenska" },
  { code: "da", name: "Dansk" },
  { code: "fi", name: "Suomi" },
  { code: "no", name: "Norsk" },
  { code: "pl", name: "Polski" },
  { code: "hr", name: "Hrvatski" },
  { code: "cs", name: "Čeština" },
  { code: "sl", name: "Slovenščina" },
  { code: "bg", name: "Български" },
  { code: "el", name: "Ελληνικά" },
  { code: "tr", name: "Türkçe" },
  { code: "ja", name: "日本語" },
  { code: "ko", name: "한국어" },
];
